name: virtspace
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - pydantic
  - sqlalchemy
  - asyncpg
  - python-dotenv
  - pytest
  - pillow
  - psycopg2
  - requests
  - pip
  - pip:
      - uvicorn[standard]
      - passlib[bcrypt]
      - httpx
      - alembic
      - supabase
      - pydantic-settings
      - python-jose
      - celery[redis]
      - razorpay