"""Jobs table

Revision ID: 4fa289a3da2b
Revises: ecb42a4e879c
Create Date: 2025-05-16 13:46:23.018723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa289a3da2b'
down_revision: Union[str, None] = 'ecb42a4e879c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_jobs', sa.Column('storage_path', sa.String(), nullable=True))
    op.drop_column('image_jobs', 'final_image_url')
    op.drop_column('images', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('image_jobs', sa.Column('final_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('image_jobs', 'storage_path')
    # ### end Alembic commands ###
