"""Initial migration

Revision ID: ecb42a4e879c
Revises: 
Create Date: 2025-05-15 18:12:35.661718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb42a4e879c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('image_type', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('RESIZE', 'THUMBNAIL', 'GRAYSCALE', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='imagestatus'), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('final_image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_jobs')
    op.drop_table('images')
    # ### end Alembic commands ###
